### ISSUE TITLE
Edit > Transform detector produces error

### ISSUE THREAD

**Issue by saransh13** [HEXRD/hexrdgui#1335]
`Traceback (most recent call last):
  File "/Users/soderlind3/hexrdgui/hexrd/ui/transform_dialog.py", line 76, in apply_transforms
    ilm.begin_processing(postprocess=True)
  File "/Users/soderlind3/hexrdgui/hexrd/ui/image_load_manager.py", line 143, in begin_processing
    thread_pool = QThreadPool(self.parent)
TypeError: 'PySide2.QtCore.QThreadPool.__init__' called with wrong argument types:
  PySide2.QtCore.QThreadPool.__init__(builtin_function_or_method)
Supported signatures:
  PySide2.QtCore.QThreadPool.__init__(typing.Optional[PySide2.QtCore.QObject] = None)`

**Comment by psavery** [comment]
@bnmajor Since the `ImageLoadManager` inherits from `QObject`, it has a `parent()` function which returns the `QObject`'s parent.

However, I see we are setting `self.parent = ...` in `read_data()` as well. The issue above must have occurred before that was set.

In any case, to avoid the name conflict, perhaps we should name `self.parent` to something else? Then in the `QThreadPool` function, we can probably pass in `self` as the parent instead of `self.parent` I think?

**Comment by bnmajor** [comment]
@saransh13 Are you able to provide a little more context as to when you saw this bug? Just loading a config and images and trying to apply a transform (to single images or all) I am not seeing this.

**Comment by bnmajor** [comment]
@psavery I've opened a PR that at least addresses the issues that you raised above, thank you!

@saransh13 Please feel free to try #1341 when you have a chance as this may be the issue (as Patrick pointed out), but I was unable to reproduce the error so I am not positive that this is the solution

**Comment by psavery** [comment]
Hi @bnmajor. It appears that this issue occurs if you load in a state file and then try to run `Edit -> Transform Detector`. I believe this is because the `ImageLoadManager().read_data()` function does not run when you load in a state file, and therefore the `ui_parent` is not set. I'll send you an example state file so you can try it out.

After merging #1341, the error displayed is now as follows:
```python
Traceback (most recent call last):
  File "/home/patrick/virtualenvs/hexrd/src/hexrdgui/hexrd/ui/transform_dialog.py", line 76, in apply_transforms
    ilm.begin_processing(postprocess=True)
  File "/home/patrick/virtualenvs/hexrd/src/hexrdgui/hexrd/ui/image_load_manager.py", line 143, in begin_processing
    thread_pool = QThreadPool(self.ui_parent)
AttributeError: 'ImageLoadManager' object has no attribute 'ui_parent'. Did you mean: 'parent'?
```

I think we need to figure out what needs to happen in order to be able to run these transforms from loading in a state file rather than loading in regular image files.

**Comment by bnmajor** [comment]
@psavery Thanks for figuring this out! I'll work on debugging :+1:
